"""Render a :class:`~huntkit.report.builder.Report` to Markdown, HTML, or JSON.

Each renderer walks the same model, so the three formats never disagree.
Markdown is the canonical, diff-friendly format; HTML is a self-contained,
print-ready page (inline CSS, no external assets); JSON is the machine form.
"""

from __future__ import annotations

import html as _html
import json
import time

from ..intel import Signal
from ..knowledge import Playbook
from .builder import Report

_GEN_BY = "Generated by HuntKit — for authorised testing only."


def _ts(epoch: float) -> str:
    return time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(epoch))


def _notable(report: Report) -> list[Signal]:
    """High/Critical single signals — the infra exposures worth calling out."""
    return sorted(
        (s for s in report.intel.signals if int(s.severity) >= 4),
        key=lambda s: (-int(s.severity), s.host),
    )


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------
def to_json(report: Report) -> str:
    return json.dumps(report.to_dict(), indent=2)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------
def _md_table(headers: list[str], rows: list[tuple[str, ...]]) -> list[str]:
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    out += ["| " + " | ".join(row) + " |" for row in rows]
    out.append("")
    return out


def to_markdown(report: Report) -> str:
    intel = report.intel
    out: list[str] = [f"# HuntKit Report — {report.program}", "",
                      f"_Generated {_ts(report.generated)}_", ""]
    if report.scope_in:
        out.append(f"**In scope:** {', '.join(report.scope_in)}")
    if report.scope_out:
        out.append(f"**Out of scope:** {', '.join(report.scope_out)}")
    out.append("")

    out += ["## Summary", ""]
    out += _md_table(["Priority", "Hosts"],
                     [(label, str(n)) for label, n in intel.summary.items()])
    out += [f"{len(intel.signals)} signals across {len(intel.hosts)} hosts.", ""]

    if intel.hosts:
        out += ["## Prioritised hosts", ""]
        out += _md_table(
            ["Host", "Priority", "Score", "Signals", "Playbooks"],
            [(h.host, h.priority.label, str(h.score), str(len(h.signals)),
              ", ".join(h.playbooks[:4]) or "—") for h in intel.hosts],
        )

    paths = intel.attack_paths()
    if paths:
        out += ["## Attack paths", ""]
        rows = []
        for p in paths:
            where = ", ".join(p.hosts[:4]) + (" …" if len(p.hosts) > 4 else "")
            rows.append((p.name, f"`{p.playbook}`", p.severity.label, str(len(p.hosts)), where))
        out += _md_table(["Playbook", "id", "Severity", "Hosts", "Where"], rows)

    hot = _notable(report)
    if hot:
        out += ["## Notable exposures", ""]
        out += _md_table(
            ["Severity", "Host", "Finding", "Evidence"],
            [(s.severity.label, s.host, s.title, s.evidence) for s in hot],
        )

    out += ["## Recon surface", ""]
    out += _md_table(["Stage", "Count"],
                     [(label, str(n)) for label, n in report.recon.items()])

    if report.playbooks:
        out += ["## Playbooks", "",
                "The bug classes this surface points at, in priority order.", ""]
        for pb in report.playbooks:
            out.append(pb.to_markdown(level=3))
            out.append("")

    out += ["---", "", _GEN_BY]
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------
_CSS = """
:root { --bg:#ffffff; --fg:#1f2933; --muted:#6b7280; --line:#e5e7eb; --accent:#0f766e; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
  font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width: 900px; margin: 0 auto; padding: 40px 24px 80px; }
h1 { font-size: 1.9rem; margin: 0 0 4px; }
h1 .muted { font-weight: 400; }
h2 { font-size: 1.25rem; margin: 2.2rem 0 .8rem; padding-bottom:.3rem; border-bottom:2px solid var(--line); }
h3 { font-size: 1.05rem; margin: 1.6rem 0 .4rem; }
h4 { font-size: .8rem; text-transform: uppercase; letter-spacing:.04em; color: var(--muted); margin: 1rem 0 .3rem; }
p { margin: .5rem 0; }
.meta, .muted { color: var(--muted); }
.meta { margin: 2px 0; font-size: .9rem; }
code { background:#f3f4f6; padding:1px 5px; border-radius:4px; font-size:.85em; }
a { color: var(--accent); }
table { border-collapse: collapse; width:100%; margin:.4rem 0 1rem; font-size:.9rem; }
th, td { text-align:left; padding:7px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
th { font-size:.72rem; text-transform:uppercase; letter-spacing:.04em; color:var(--muted); }
tbody tr:hover { background:#fafafa; }
pre { background:#0f172a; color:#e2e8f0; padding:12px 14px; border-radius:8px; overflow-x:auto;
  font:13px/1.5 "SF Mono",ui-monospace,Menlo,Consolas,monospace; }
ul { margin:.3rem 0; padding-left:1.2rem; }
li { margin:.15rem 0; }
.cards { display:flex; gap:12px; flex-wrap:wrap; margin:.6rem 0 1rem; }
.card { flex:1; min-width:110px; border:1px solid var(--line); border-radius:10px; padding:14px 16px; }
.card-n { font-size:1.8rem; font-weight:700; line-height:1; }
.card-l { font-size:.8rem; color:var(--muted); margin-top:4px; }
.card-critical { border-color:#7f1d1d; } .card-critical .card-n { color:#7f1d1d; }
.card-high { border-color:#dc2626; } .card-high .card-n { color:#dc2626; }
.card-medium { border-color:#d97706; } .card-medium .card-n { color:#b45309; }
.card-low { border-color:#16a34a; } .card-low .card-n { color:#15803d; }
.sev { display:inline-block; padding:1px 8px; border-radius:999px; font-size:.75rem; font-weight:600; }
.sev-critical { background:#7f1d1d; color:#fff; }
.sev-high { background:#fee2e2; color:#991b1b; }
.sev-medium { background:#ffedd5; color:#9a3412; }
.sev-low { background:#dcfce7; color:#166534; }
.sev-informational { background:#e0f2fe; color:#075985; }
.pb { border:1px solid var(--line); border-radius:12px; padding:4px 20px 16px; margin:1rem 0; }
footer { margin-top:3rem; padding-top:1rem; border-top:1px solid var(--line); color:var(--muted); font-size:.85rem; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#0b1220; --fg:#e5e7eb; --muted:#9ca3af; --line:#1f2937; --accent:#5eead4; }
  code { background:#1f2937; } tbody tr:hover { background:#111827; }
  .sev-high { background:#450a0a; color:#fca5a5; } .sev-medium { background:#451a03; color:#fdba74; }
  .sev-low { background:#052e16; color:#86efac; } .sev-informational { background:#082f49; color:#7dd3fc; }
}
@media print { .pb, .card { break-inside: avoid; } body { background:#fff; color:#000; } }
"""


def _chip(sev) -> str:
    return f"<span class='sev sev-{sev.style}'>{_html.escape(sev.label)}</span>"


def _html_table(headers: list[str], rows: list[tuple[str, ...]]) -> str:
    head = "".join(f"<th>{_html.escape(h)}</th>" for h in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>" for row in rows
    )
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _playbook_html(pb: Playbook) -> str:
    p: list[str] = ["<section class='pb'>",
                    f"<h3>{_html.escape(pb.title)} {_chip(pb.severity)} "
                    f"<code>{_html.escape(pb.id)}</code></h3>",
                    f"<p>{_html.escape(pb.summary)}</p>",
                    f"<p class='muted'><strong>When:</strong> {_html.escape(pb.when)}</p>"]

    def block(head: str, items: tuple[str, ...]) -> None:
        if not items:
            return
        p.append(f"<h4>{head}</h4><ul>")
        p.extend(f"<li>{_html.escape(it)}</li>" for it in items)
        p.append("</ul>")

    block("Detection", pb.detection)
    if pb.payloads:
        p.append("<h4>Payloads</h4><pre>" + _html.escape("\n".join(pb.payloads)) + "</pre>")
    block("Bypasses", pb.bypasses)
    if pb.tools:
        p.append("<h4>Go-to tools</h4><p>" + _html.escape(", ".join(pb.tools)) + "</p>")
    if pb.references:
        p.append("<h4>References</h4><ul>")
        p += [f"<li><a href='{_html.escape(r.url)}'>{_html.escape(r.name)}</a></li>"
              for r in pb.references]
        p.append("</ul>")
    p.append("</section>")
    return "".join(p)


def to_html(report: Report) -> str:
    intel = report.intel
    esc = _html.escape
    h: list[str] = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>HuntKit Report — {esc(report.program)}</title>",
        f"<style>{_CSS}</style>",
        "</head><body><main class='wrap'>",
        f"<h1>HuntKit Report <span class='muted'>— {esc(report.program)}</span></h1>",
        f"<p class='meta'>Generated {_ts(report.generated)}</p>",
    ]
    if report.scope_in:
        h.append(f"<p class='meta'><strong>In scope:</strong> {esc(', '.join(report.scope_in))}</p>")
    if report.scope_out:
        h.append(f"<p class='meta'><strong>Out of scope:</strong> {esc(', '.join(report.scope_out))}</p>")

    h.append("<h2>Summary</h2><div class='cards'>")
    for label, n in intel.summary.items():
        h.append(f"<div class='card card-{label.lower()}'>"
                 f"<div class='card-n'>{n}</div><div class='card-l'>{label}</div></div>")
    h.append("</div>")
    h.append(f"<p>{len(intel.signals)} signals across {len(intel.hosts)} hosts.</p>")

    if intel.hosts:
        h.append("<h2>Prioritised hosts</h2>")
        h.append(_html_table(
            ["Host", "Priority", "Score", "Signals", "Playbooks"],
            [(esc(x.host), _chip(x.priority), str(x.score), str(len(x.signals)),
              esc(", ".join(x.playbooks[:4]) or "—")) for x in intel.hosts],
        ))

    paths = intel.attack_paths()
    if paths:
        h.append("<h2>Attack paths</h2>")
        rows = []
        for p in paths:
            where = esc(", ".join(p.hosts[:4])) + (" …" if len(p.hosts) > 4 else "")
            rows.append((esc(p.name), f"<code>{esc(p.playbook)}</code>",
                         _chip(p.severity), str(len(p.hosts)), where))
        h.append(_html_table(["Playbook", "id", "Severity", "Hosts", "Where"], rows))

    hot = _notable(report)
    if hot:
        h.append("<h2>Notable exposures</h2>")
        h.append(_html_table(
            ["Severity", "Host", "Finding", "Evidence"],
            [(_chip(s.severity), esc(s.host), esc(s.title), esc(s.evidence)) for s in hot],
        ))

    h.append("<h2>Recon surface</h2>")
    h.append(_html_table(["Stage", "Count"],
                         [(esc(label), str(n)) for label, n in report.recon.items()]))

    if report.playbooks:
        h.append("<h2>Playbooks</h2>")
        h.append("<p class='muted'>The bug classes this surface points at, in priority order.</p>")
        h += [_playbook_html(pb) for pb in report.playbooks]

    h.append(f"<footer>{esc(_GEN_BY)}</footer>")
    h.append("</main></body></html>")
    return "\n".join(h) + "\n"
